// src/ClickToSource.vue
<script setup lang="ts">
import { onMounted, onUnmounted, watch } from "vue";
import { ClickToSourceOverlay, type EditorProtocol, type ModifierLocation } from "./overlay-core";

const props = withDefaults(
  defineProps<{
    editorProtocol?: EditorProtocol;
    /**
     * Which modifier key location to respond to.
     * - "any" (default): Respond to both left and right modifier keys
     * - "left": Only respond to left-side modifier keys
     * - "right": Only respond to right-side modifier keys
     */
    modifierLocation?: ModifierLocation;
  }>(),
  {
    editorProtocol: "cursor",
    modifierLocation: "any",
  }
);

let overlay: ClickToSourceOverlay | null = null;

onMounted(() => {
  overlay = new ClickToSourceOverlay({
    editorProtocol: props.editorProtocol,
    modifierLocation: props.modifierLocation,
  });
  overlay.mount();
});

onUnmounted(() => {
  overlay?.unmount();
  overlay = null;
});

watch(
  () => props.editorProtocol,
  (protocol) => {
    overlay?.setEditorProtocol(protocol);
  }
);

watch(
  () => props.modifierLocation,
  (location) => {
    overlay?.setModifierLocation(location);
  }
);
</script>

<template>
  <slot></slot>
</template>

// src/click-to-source.component.ts
import {
  Component,
  Input,
  OnInit,
  OnDestroy,
  OnChanges,
  SimpleChanges,
} from "@angular/core";
import { ClickToSourceOverlay, type EditorProtocol, type ModifierLocation } from "./overlay-core";

@Component({
  selector: "click-to-source",
  standalone: true,
  template: "<ng-content></ng-content>",
})
export class ClickToSourceComponent implements OnInit, OnDestroy, OnChanges {
  @Input() editorProtocol: EditorProtocol = "cursor";
  /**
   * Which modifier key location to respond to.
   * - "any" (default): Respond to both left and right modifier keys
   * - "left": Only respond to left-side modifier keys
   * - "right": Only respond to right-side modifier keys
   */
  @Input() modifierLocation: ModifierLocation = "any";

  private overlay: ClickToSourceOverlay | null = null;

  ngOnInit(): void {
    this.overlay = new ClickToSourceOverlay({
      editorProtocol: this.editorProtocol,
      modifierLocation: this.modifierLocation,
    });
    this.overlay.mount();
  }

  ngOnDestroy(): void {
    this.overlay?.unmount();
    this.overlay = null;
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["editorProtocol"] && this.overlay) {
      this.overlay.setEditorProtocol(this.editorProtocol);
    }
    if (changes["modifierLocation"] && this.overlay) {
      this.overlay.setModifierLocation(this.modifierLocation);
    }
  }
}
